<template>
  <div class="pt-24 pb-16">
    <article
      class="max-w-3xl mx-auto px-6 [&_h2]:font-display [&_h2]:text-[1.375rem] [&_h2]:text-charcoal [&_h2]:mt-8 [&_h2]:mb-3 [&_p]:text-[0.9375rem] [&_p]:leading-[1.7] [&_p]:text-warm-gray [&_p]:mb-3 [&_li]:text-[0.9375rem] [&_li]:leading-[1.7] [&_li]:text-warm-gray [&_li]:mb-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:mb-4 [&_section]:mb-6"
    >
      <h1 class="font-display text-3xl md:text-4xl text-charcoal mb-8">
        Terms of Service
      </h1>
      <p class="text-warm-gray text-sm mb-6">Last updated: {{ lastUpdated }}</p>

      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By downloading, installing, or using Wedlune, you agree to these
          Terms of Service. If you do not agree, please do not use the app.
        </p>
      </section>

      <section>
        <h2>2. Description of Service</h2>
        <p>
          Wedlune is a wedding planning app that provides questionnaire-based
          planning, AI-powered recommendations, timeline management, local task
          reminders, guest tracking with RSVP, budget management, vendor contact
          management, seating arrangements, attire and transport tracking,
          legal-document storage, photo gallery, and partner collaboration.
          Some features may be limited under the free plan and require a
          premium subscription. Free-tier users may see Google AdMob banner ads.
        </p>
      </section>

      <section>
        <h2>3. User Accounts</h2>
        <ul>
          <li>
            You must be at least 16 years old, or the minimum digital-consent
            age in your country, to create an account.
          </li>
          <li>
            You must provide a valid email address and accurate information.
          </li>
          <li>
            You are responsible for keeping your login credentials confidential
            and for activity under your account.
          </li>
          <li>
            You may invite your partner to share a wedding plan. Shared data is
            visible according to the partner permissions you choose.
          </li>
        </ul>
      </section>

      <section>
        <h2>4. User Content</h2>
        <p>
          You retain ownership of content you upload or create, including
          photos, guest information, legal documents, and wedding details. You
          grant us a limited license to store, process, display, and sync that
          content solely to provide the service. If you collaborate with a
          partner, content is shared according to the selected permissions.
        </p>
      </section>

      <section>
        <h2>5. AI-Generated Content</h2>
        <p>
          Recommendations and timelines generated by AI features are suggestions
          only and may include inaccurate information such as incorrect vendor
          details, pricing, contact information, legal requirements, or
          scheduling assumptions. You are responsible for independently
          verifying all AI-generated suggestions before acting on them.
        </p>
      </section>

      <section>
        <h2>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use Wedlune for any unlawful purpose.</li>
          <li>Upload offensive, harmful, infringing, or unlawful content.</li>
          <li>Attempt to access another user's data or bypass access controls.</li>
          <li>Reverse-engineer, decompile, or disassemble the app.</li>
          <li>Use automated tools to scrape or misuse the service.</li>
        </ul>
      </section>

      <section>
        <h2>7. Subscriptions</h2>
        <p>
          Premium features may be offered through in-app purchases and
          subscriptions processed by Google Play and managed through RevenueCat.
          Subscription cancellation and billing management are handled by the
          relevant app store. Deleting your Wedlune account does not by itself
          cancel an active app-store subscription.
        </p>
      </section>

      <section>
        <h2>8. Service Availability</h2>
        <p>
          We strive to maintain reliable service but do not guarantee
          uninterrupted availability. Features requiring internet connectivity,
          including AI recommendations and data sync, may be unavailable during
          outages. Offline cached data may remain accessible in the app.
        </p>
      </section>

      <section>
        <h2>9. Termination And Account Deletion</h2>
        <p>
          You may delete your account at any time from Settings → Delete
          Account in the app or request deletion through our
          <NuxtLink
            to="/delete-account"
            class="text-champagne-gold hover:text-deep-gold"
            >account deletion page</NuxtLink
          >. We may suspend or terminate accounts that violate these terms.
          Upon termination, your data will be deleted or retained only as
          described in our
          <NuxtLink
            to="/privacy"
            class="text-champagne-gold hover:text-deep-gold"
            >Privacy Policy</NuxtLink
          >.
        </p>
      </section>

      <section>
        <h2>10. Limitation of Liability</h2>
        <p>
          Wedlune is provided "as is" without warranties of any kind to the
          fullest extent permitted by law. Nothing in these terms limits rights
          that cannot legally be limited, including mandatory EU consumer
          rights. We are not liable for indirect or consequential damages
          arising from use of the app, including planning errors, data loss, or
          reliance on AI suggestions.
        </p>
      </section>

      <section>
        <h2>11. Changes to Terms</h2>
        <p>
          We may update these terms from time to time. Material changes will be
          communicated through the app or by email before they take effect where
          required. If you do not agree to updated terms, stop using the app and
          you may delete your account.
        </p>
      </section>

      <section>
        <h2>12. Contact</h2>
        <p>
          For questions about these terms, contact
          <a
            href="mailto:hi@wedlune.com"
            class="text-champagne-gold hover:text-deep-gold"
            >hi@wedlune.com</a
          >.
        </p>
      </section>
    </article>
  </div>
</template>

<script setup lang="ts">
const lastUpdated = "July 14, 2026";

useSeoMeta({
  title: "Terms of Service — Wedlune",
  description:
    "Wedlune Terms of Service — rules and guidelines for using our AI wedding planning app.",
  ogTitle: "Terms of Service — Wedlune",
  ogDescription:
    "Wedlune Terms of Service — rules and guidelines for using our AI wedding planning app.",
});

useSchemaOrg([
  defineWebPage({
    name: "Terms of Service — Wedlune",
    description:
      "Wedlune Terms of Service — rules and guidelines for using our AI wedding planning app.",
  }),
]);
</script>
